title: B2C Commerce Developer Documentation
# Disable caching
cache: false
theme: jekyll-theme-cayman
plugins:
  - jekyll_search
  - jekyll-relative-links
  - jekyll-redirect-from
include:
  - _includes
  - _layouts
  - _sass
  - assets/css
  - assets/js
  - docs/
baseurl: "/"
search:
  json: true
